$add_ssh_key = <<-SCRIPT
	echo adding ssh_key
	cat /devops/config/id_rsa_vagrant.pub >> .ssh/authorized_keys
SCRIPT

Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/bionic64"

	# WORDPRESS DB SERVER
	config.vm.define "mysqlserver" do |mysqlserver|
		mysqlserver.vm.network "private_network", ip: "172.28.128.9"

		mysqlserver.vm.provider "virtualbox" do |v|
			v.memory = 2048
			v.cpus = 1
		end

		mysqlserver.vm.synced_folder ".", "/vagrant", disabled: true	  
		mysqlserver.vm.synced_folder "./config",	 "/devops/config"

		mysqlserver.vm.provision "shell", inline: $add_ssh_key
	end

	# WORDPRESS APP SERVER
	config.vm.define "appserver" do |appserver|
		appserver.vm.network "private_network", ip: "172.28.128.8"

		appserver.vm.provider "virtualbox" do |v|
			v.memory = 1024
			v.cpus = 1
		end

		appserver.vm.synced_folder ".", "/vagrant", disabled: true	  
		appserver.vm.synced_folder "./config",	 "/devops/config"

		appserver.vm.provision "shell", inline: $add_ssh_key

		appserver.vm.provision "ansible" do |ansible|
			ansible.limit = "all"
			ansible.inventory_path = "./config/ansible/hosts"
		 	ansible.playbook = "./config/ansible/playbook.yml"
		end
	end

end