$mysql_script = <<-SCRIPT
	echo Installing mysql...
	apt-get -q update && apt-get -q install -y mysql-server-5.7
SCRIPT

$wildfly = <<-SCRIPT
	echo Downloading wildfly
	wget -q https://download.jboss.org/wildfly/17.0.0.Final/wildfly-17.0.0.Final.zip
	unzip wildfly-17.0.0.Final.zip -d /opt/
SCRIPT


Vagrant.configure("2") do |config|
  # ubuntu image
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.define "appserver" do |appserver|
	# network configuration
	appserver.vm.network "forwarded_port", guest: 80,   host: 80
	appserver.vm.network "forwarded_port", guest: 8080, host: 8080
	appserver.vm.network "forwarded_port", guest: 9990, host: 9990
	appserver.vm.network "public_network", type: "dhcp"

	# computing resources
	appserver.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 1
	end
	  
	# sync folder
	appserver.vm.synced_folder ".", "/vagrant", disabled: true

	# package configuration
	appserver.vm.provision :shell, inline: "apt-get -q update && apt-get -q install -y nginx"
	appserver.vm.provision :shell, inline: "apt-get -q install -y unzip"
	appserver.vm.provision :shell, inline: "apt-get -q install -y openjdk-11-jre-headless"

	# install wildfly
	appserver.vm.provision "shell", inline: $wildfly
  end	


  config.vm.define "mysqldb" do |mysql|
	# network configuration
	mysql.vm.network "forwarded_port", guest: 3306, host: 3307
	mysql.vm.network "public_network", type: "dhcp"

	# computing resources
	mysql.vm.provider "virtualbox" do |v|
		v.memory = 4096
		v.cpus = 2
	end

	# sync folder
	mysql.vm.synced_folder ".", "/vagrant", disabled: true
	mysql.vm.synced_folder "./db_files", "/devops/db_files"
	mysql.vm.synced_folder "./config", "/devops/config"

	# load keys
	mysql.vm.provision "shell",
	inline: "cat /devops/config/id_rsa_vagrant.pub >> .ssh/authorized_keys"

	# install mysql
	mysql.vm.provision "shell", inline: $mysql_script

	# copy mysql config file
	mysql.vm.provision "shell",
	inline: "cat /devops/db_files/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf && \
			service mysql restart"
  end	
  
end