$mysql_script = <<-SCRIPT
	echo Installing mysql...
	apt-get -q update && apt-get -q install -y mysql-server-5.7
SCRIPT

$wildfly_script = <<-SCRIPT
	echo Downloading wildfly
	wget -q https://download.jboss.org/wildfly/17.0.0.Final/wildfly-17.0.0.Final.zip
	unzip wildfly-17.0.0.Final.zip -d /opt/
SCRIPT


Vagrant.configure("2") do |config|
  # ubuntu image
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.define "appserver" do |appserver|
	# network configuration
	appserver.vm.network "forwarded_port", guest: 80,   host: 80
	appserver.vm.network "forwarded_port", guest: 8080, host: 8080
	appserver.vm.network "forwarded_port", guest: 9990, host: 9990
	appserver.vm.network "private_network", ip: "172.28.128.6"

	# computing resources
	appserver.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 1
	end
	  
	# sync folder
	appserver.vm.synced_folder ".", "/vagrant", disabled: true

	# package configuration
	appserver.vm.provision :shell, inline: "apt-get -q update && apt-get -q install -y nginx"
	appserver.vm.provision :shell, inline: "apt-get -q install -y unzip"
	appserver.vm.provision :shell, inline: "apt-get -q install -y openjdk-11-jre-headless"
	appserver.vm.provision :shell, inline: "apt-get -q install -y openjdk-11-jre-headless"
	appserver.vm.provision :shell, inline: "apt-get -q install -y python"

	# install wildfly
	appserver.vm.provision "shell", inline: $wildfly_script
  end	

  config.vm.define "mysqldb" do |mysql|
	# network configuration
	mysql.vm.network "forwarded_port", guest: 3306, host: 3307
	mysql.vm.network "private_network", ip: "172.28.128.7"

	# computing resources
	mysql.vm.provider "virtualbox" do |v|
		v.memory = 4096
		v.cpus = 2
	end

	# sync folder
	mysql.vm.synced_folder ".", "/vagrant", disabled: true
	mysql.vm.synced_folder "./db_files", "/devops/db_files"
	mysql.vm.synced_folder "./config", "/devops/config"

	# package configuration
	mysql.vm.provision :shell, inline: "apt-get -q update && apt-get install -y python"

	# load ssh key
	mysql.vm.provision "shell",
		inline: "cat /devops/config/id_rsa_vagrant.pub >> .ssh/authorized_keys"

	# run ansible
	mysql.vm.provision "ansible" do |ansible|
		ansible.inventory_path = "./config/ansible/hosts"
    	ansible.playbook = "./config/ansible/playbook.yml"
  	end

  end

end