$add_ssh_key = <<-SCRIPT
	echo adding ssh_key
	cat /devops/config/id_rsa_vagrant.pub >> .ssh/authorized_keys
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  # WORDPRESS APP SERVER
  config.vm.define "wp_app" do |wp_app|
	wp_app.vm.network "private_network", ip: "172.28.128.8"

	wp_app.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
	end

	wp_app.vm.synced_folder ".", "/vagrant", disabled: true	  
	wp_app.vm.synced_folder "./config",	 "/devops/config"

  	wp_app.vm.provision "shell", inline: $add_ssh_key
  	wp_app.vm.provision :shell, inline: "apt-get -q update"

	# run ansible
	#wp_app.vm.provision "ansible" do |ansible|
	#	ansible.inventory_path = "./config/ansible/hosts"
    # 	ansible.playbook = "./config/ansible/wordpress/playbook.yml"
  	#end
  end

  # WORDPRESS DB SERVER
  config.vm.define "wp_mysql" do |wp_mysql|
	wp_mysqlvm.network "private_network", ip: "172.28.128.9"

	wp_mysqlvm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 1
	end

	wp_mysqlvm.synced_folder ".", "/vagrant", disabled: true	  
	wp_mysqlvm.synced_folder "./config",	 "/devops/config"

  	wp_mysqlvm.provision "shell", inline: $add_ssh_key
  	wp_mysqlvm.provision :shell, inline: "apt-get -q update"

	# run ansible
	#wp_mysqlvm.provision "ansible" do |ansible|
	#	ansible.inventory_path = "./config/ansible/hosts"
    # 	ansible.playbook = "./config/ansible/mysql/playbook.yml"
  	#end
  end

end