---
- name: Install mysql
  apt:
    update_cache: yes
    name: 
      - mysql-server-5.7
      - python3-mysqldb
    state: latest
  become: yes

- name: Create mysql database - wordpress_db
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present 
  become: yes

- name: Create a admin user
  mysql_user:
    name: "{{ wp_db_admin_user }}"
    password: "{{ wp_db_admin_pass }}"
    priv: '*.*:ALL'
    state: present
    host: '%'
  become: yes

- name: Create a wordpress user
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_pass }}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: '%'
  become: yes

- name: enable external connection
  replace:
    path: '/etc/mysql/mysql.conf.d/mysqld.cnf'
    regexp:  'bind-address'
    replace: '#bind-address'
  become: yes
  notify: restart_mysql