- hosts: all
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes

  tasks:
    - name: 'Install MySQL Server'
      apt:
        update_cache: yes
        cache_valid_time: 3600 #1 hour
        name: ["mysql-server-5.7", "python-mysqldb"]
        state: latest
      become: yes

    - name: 'MySQL - Create admin user'
      mysql_user:
        login_user: root
        name: admin
        password: admin
        priv: '*.*:ALL'
        host: '%'
        state: present
      become: yes

    - name: 'Copy mysqld.cnf file'
      copy:
        src:  /home/sylvioneto/Downloads/cursos/vagrant_dev/env_dev_with_ansible/db_files/mysqld.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        owner: root
        group: root
        mode: 0644
      become: yes
      notify:
        - restart mysql