---
- hosts: wp_mysql

  tasks:
    - name: Install mysql
      apt:
        update_cache: yes
        name: 
          - mysql-server-5.7
          - python3-mysqldb
        state: latest
      become: yes

    - name: Create mysql database - wordpress_db
      mysql_db:
        name: wordpress_db
        state: present 
      become: yes

    - name: Create a admin user
      mysql_user:
        name: admin
        password: admin1
        priv: '*.*:ALL'
        state: present
      become: yes

    - name: Create a wordpress user
      mysql_user:
        name: wordpress_user
        password: wordpress_pass
        priv: 'wordpress_db.*:ALL'
        state: present
      become: yes