---
- hosts: all
  tasks:
    - name: Install PHP, Apache2 and Mysql dependencies
      apt:
        update_cache: yes
        name: 
          - php7.2
          - apache2
          - libapache2-mod-php7.2
          - php7.2-cli
          - php7.2-common
          - php7.2-mbstring
          - php7.2-gd
          - php7.2-intl
          - php7.2-xml
          - php7.2-mysql
          - php7.2-zip
          - mysql-server-5.7
          - python3-mysqldb
        state: latest
      become: yes

    - name: Create mysql database - wordpress_db
      mysql_db:
        name: wordpress_db
        state: present 
      become: yes

    - name: Create a admin user
      mysql_user:
        name: admin
        password: admin1
        priv: '*.*:ALL'
        state: present
      become: yes

    - name: Create a wordpress user
      mysql_user:
        name: wordpress_user
        password: wordpress_pass
        priv: 'wordpress_db.*:ALL'
        state: present
      become: yes  