$add_ssh_key = <<-SCRIPT
	echo adding ssh_key
	cat /devops/config/id_rsa_vagrant.pub >> .ssh/authorized_keys
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  
  config.vm.provision "shell",	inline: $add_ssh_key

  config.vm.define "appserver" do |appserver|
	appserver.vm.network "private_network", ip: "172.28.128.6"

	appserver.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 1
	end
	  
	appserver.vm.synced_folder ".", "/vagrant", disabled: true
	appserver.vm.synced_folder "./config", "/devops/config"

	appserver.vm.provision "ansible" do |ansible|
		ansible.inventory_path = "./config/ansible/hosts"
    	ansible.playbook = "./config/ansible/appserver/playbook.yml"
  	end
  end	

  config.vm.define "mysqlserver" do |mysqlserver|
	mysqlserver.vm.network "private_network", ip: "172.28.128.7"

	mysqlserver.vm.provider "virtualbox" do |v|
		v.memory = 4096
		v.cpus = 2
	end

	mysqlserver.vm.synced_folder ".", "/vagrant", disabled: true
	mysqlserver.vm.synced_folder "./db_files", "/devops/db_files"
	mysqlserver.vm.synced_folder "./config", "/devops/config"

	mysqlserver.vm.provision "ansible" do |ansible|
		ansible.inventory_path = "./config/ansible/hosts"
    	ansible.playbook = "./config/ansible/mysql/playbook.yml"
  	end

  end

end